const fs = require("fs");
const path = require("path");

async function syncRepos() {
  console.log("Fetching latest GSSoC repositories...");
  try {
    const res = await fetch("https://gssoc.girlscript.org/api/projects");
    if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
    
    const data = await res.json();
    const repos = data.projects.map((p: any) => p.owner_repo.toLowerCase());
    
    // Deduplicate and sort
    const uniqueRepos = Array.from(new Set(repos)).sort();
    
    const content = `// All ${uniqueRepos.length} officially registered GSSoC 2026 projects
// Source: https://gssoc.girlscript.org/api/projects
// Auto-generated by scripts/sync-repos.ts
// All values are lowercase owner/repo for case-insensitive matching

const REPOS: string[] = [
${uniqueRepos.map((r: unknown) => `  "${r}"`).join(",\n")}
];

export const GSSOC_REPO_SET = new Set(REPOS);
`;

    const filePath = path.join(process.cwd(), "src/data/gssoc-repos.ts");
    fs.writeFileSync(filePath, content);
    console.log(`Successfully synced ${uniqueRepos.length} repositories to src/data/gssoc-repos.ts!`);
  } catch (error) {
    console.error("Failed to sync GSSoC repos:", error);
    process.exit(1);
  }
}

syncRepos();
